/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package siv.receiver;

import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.net.ServerSocket;
import java.nio.*;
import java.nio.channels.*;
import java.nio.channels.spi.*;
import java.nio.charset.*;
import java.nio.channels.SelectionKey;
import java.nio.channels.ServerSocketChannel;
import java.nio.channels.spi.SelectorProvider;
import java.nio.file.Paths;
import java.net.*;
import java.util.*;

/**
 *
 * @author Dmitry_Lukashin
 */
public class ImageViewerUI extends javax.swing.JFrame {

    String imageFolder;
    Image screenImage;
    int w,h;
    
    /**
     * Creates new form MainFrame
     */
    public ImageViewerUI() {
        initComponents();
        
        //Set full screen mode for window
        GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().setFullScreenWindow(this);

        String sPath = GetCurrentDirectory();
        
        String sImgPath = Paths.get(sPath).getParent().toString() + "\\Images\\";
        
        File file = new File(sImgPath);
        File[] images = file.listFiles();
        
        if (images == null || images.length == 0) return;

        String imgPath = images[0].getPath();
        screenImage = Toolkit.getDefaultToolkit().getImage(imgPath);

        w = getWidth();
        h = getHeight();
 
        InitChannel();
    }

    private String GetCurrentDirectory()
    {
        String curDir = null;
        File dir1 = new File(".");
        
        try
        {
            curDir = dir1.getCanonicalPath();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
        return curDir;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setLabelFor(this);
        jLabel1.setText("Нажмите Esc для выхода");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(26, 26, 26)
                .add(jLabel1)
                .addContainerGap(246, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(49, 49, 49)
                .add(jLabel1)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        //
        int keyCode = evt.getKeyCode();
        if (evt.getKeyCode() == 27)
        {
            System.exit(0);
        }        
    }//GEN-LAST:event_formKeyPressed
    
    public void paint(Graphics g)
    {
        
        if (screenImage != null)
        {
            
            g.drawImage(screenImage, w/2 - screenImage.getWidth(this)/2,
                    h/2 - screenImage.getHeight(this)/2, this);
            
            g.setColor(Color.WHITE);
            g.drawString("Press Esc for exit", 0, 10);
            
        }
    }
    
    public ServerSocket openServerSocket()
    {
        int port = 4446;
        ServerSocket serverSocket = null;
        try
        {
            serverSocket = new ServerSocket(port);
        }
        catch(IOException e)
        {
            System.out.println("Could not listen on port: " + port);
            System.out.println(e.getMessage());
            System.out.println(e.getStackTrace());
            System.exit(-1);
        }
        
        return serverSocket;
    }
    
    
    private ServerSocketChannel InitChannel()
    {
        try
        {
            int port = 4450;
            Selector selector = SelectorProvider.provider().openSelector();
            ServerSocketChannel channel = ServerSocketChannel.open();
            channel.configureBlocking(false);

            InetAddress lh = InetAddress.getLocalHost();
            InetSocketAddress isa = new InetSocketAddress(lh, port);

            channel.socket().bind(isa);

            SelectionKey acceptKey = channel.register(selector, SelectionKey.OP_ACCEPT);
            
            return channel;
        }
        catch(IOException e)
        {
        }
        
        return null;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImageViewerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImageViewerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImageViewerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImageViewerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ImageViewerUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
